default: &default
  adapter: mysql2

  <% if ENV['DOCKER_COMPOSE'] %>
  host: db
  <% end %>

  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'root' %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: purchasing_development

test:
  <<: *default
  database: purchasing_test

staging:
  <<: *default
  database: no_thanks

production:
  <<: *default
  database: no_thanks
