default: &default
  adapter: mysql2

  <% if ENV['DOCKER_COMPOSE'] %>
  host: db
  <% end %>

  pool: 5
  timeout: 5000

development:
  <<: *default
  database: purchasing_development

test:
  <<: *default
  database: purchasing_test

staging:
  <<: *default
  database: no_thanks

production:
  <<: *default
  database: no_thanks

semiprod:
  <<: *default
  host: <%= ENV['SEMI_PROD_HOST'] %>
  username: <%= ENV['SEMI_PROD_USERNAME'] %>
  password: <%= ENV['SEMI_PROD_PASSWORD'] %>
  database: <%= ENV['SEMI_PROD_DATABASE'] %>

bookingin_development:
  <<: *default
  database: purchasing_development

bookingin_test:
  <<: *default
  database: purchasing_test

bookingin_staging:
  <<: *default
  database: no_thanks

bookingin_production:
  <<: *default
  database: no_thanks
