default: &default
  url: 'https://endpoints.surfdome.cc/peoplevox_endpoint/api/sku_lookup'
  key: 'P5Ft0ZgmJuqWB'
  token: 'twRduwypFJoZVYkbMe5KYuqPqG7lDxmSVxUWNP3i'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
