FROM phusion/passenger-ruby22:0.9.18

# Set correct environment variables.
ENV HOME /root

# Prepare App dir
RUN mkdir /home/app/webapp
WORKDIR /home/app/webapp
RUN mkdir /home/app/webapp/log
RUN touch /home/app/webapp/log/purchasing.json.log
RUN chown app. /home/app/webapp/log/purchasing.json.log
RUN chmod 0664 /home/app/webapp/log/

# Configure Nginx
RUN rm /etc/nginx/sites-enabled/default
ADD config/webapp.conf /etc/nginx/sites-enabled/webapp.conf
ADD config/nginx-env.conf /etc/nginx/main.d/nginx-env.conf
ADD config/passenger.conf /etc/nginx/conf.d/passenger.conf

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Bundle dependencies
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install

# Add the App
ADD . /home/app/webapp

# Enable Nginx+Passenger on boot
RUN rm -f /etc/service/nginx/down
ADD config/database-env.yml /home/app/webapp/config/database.yml

EXPOSE 80

COPY ./docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use baseimage-docker's init process.
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["start"]
