FROM 213273172953.dkr.ecr.eu-west-1.amazonaws.com/ruby_base:2.2.3
MAINTAINER Blagovest Karakashev, blagovest.karakashev@surfdome.com

# Create app directory
RUN mkdir -p /home/webapp/tmp/pids
WORKDIR /home/webapp

# Bundle dependencies
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install --deployment --without development test continuous

# ADD the App
ADD . /home/webapp
ADD ./config/database-env.yml config/database.yml

EXPOSE 80 3000

# Copy docker-entrypoint.sh
ADD ./docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Start the App
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["start"]
