source 'https://rubygems.org'
ruby '2.2.3'

gem 'active_model_serializers', '0.9.4'
gem 'puma',      '~> 2.10', '>= 2.10.2'
gem 'aws-sdk'
gem 'axlsx'
gem 'excon'
gem 'kaminari'
gem 'mysql2', '~> 0.3.17'
gem 'nokogiri', '1.6.8'
gem 'paperclip', '~> 4.3'
gem 'rails', '4.2.4'
gem 'rake'
gem 'sentry-raven'
gem 'paper_trail', '~> 4.0.0'
gem 'sidekiq'
gem "activerecord-import", "~> 0.10.0"
gem 'finishing_moves'
gem 'dropzonejs-rails'
gem 'uglifier'
gem 'sass-rails'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'

group :test do
  gem 'brakeman'                  # Always latest
  gem 'cane',                     '2.6.2'
  gem 'capybara',                 '2.4.1'
  gem "codeclimate-test-reporter"
  gem 'database_cleaner',         '1.5.1'
  gem 'factory_girl',             '4.5.0'
  gem 'faker'
  gem 'rspec_junit_formatter',    '0.2.0'
  gem 'rspec-its',                '1.0.1'
  gem 'rspec-rails',              '3.2.1'
  gem 'rspec',                    '3.2.0'
  gem 'simple_xlsx_reader'
  gem 'scss-lint',                '~> 0.37.0'
  gem 'simplecov-rcov',           '0.2.3'
  gem 'simplecov',                '0.9.2'
  gem 'tailor',                   '1.4.1'
  gem 'timecop',                  '0.8.0'
  gem 'vcr',                      '2.9.2'
  gem 'webmock',                  '1.19.0'
  gem 'jsonpath'
end

group :development do
  gem 'spring'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'shoulda'
end

group :staging, :production do
  gem 'therubyracer'
end
