source 'https://rubygems.org'
ruby '2.2.2'

gem 'responders', '~> 2.0' 
gem 'kaminari'
gem 'mysql2'
gem 'rails', '4.2.4'
gem 'rake'
gem 'sentry-raven'
gem 'paperclip', '~> 4.3'
gem 'aws-sdk'
gem 'excon'

group :test do
  gem 'brakeman'                  # Always latest
  gem 'cane',                     '2.6.2'
  gem 'capybara',                 '2.4.1'
  gem 'factory_girl',             '4.5.0'
  gem 'ffaker',                   '1.32.1'
  gem 'rspec_junit_formatter',    '0.2.0'
  gem 'rspec-its',                '1.0.1'
  gem 'rspec-rails',              '3.2.1'
  gem 'rspec',                    '3.2.0'
  gem 'scss-lint',                '~> 0.37.0'
  gem 'simplecov-rcov',           '0.2.3'
  gem 'simplecov',                '0.9.2'
  gem 'tailor',                   '1.4.1'
  gem 'timecop',                  '0.8.0'
  gem 'vcr',                      '2.9.2'
  gem 'webmock',                  '1.19.0'
end

group :development do
  gem 'spring'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry-byebug'
  gem 'pry-rails'
end
