require File.expand_path('../config/application', __FILE__)

require "./app/models/barcode"

Rails.application.load_tasks

namespace :db do
  desc "remove leading backticks"
  task :barcode_fix => :environment do
    old_barcodes = Barcode.where('barcode LIKE ?', "'%")
    puts "#{old_barcodes.length} Barcodes found"
    abort("There are no barcodes that need fixing") if old_barcodes.length < 1
    old_barcodes.each{ | barcode | 
      new_barcode = barcode.barcode[1..-1]
      Barcode::Updater.update(barcode: new_barcode, id: barcode.id)
    }
    puts "#{old_barcodes.length} Barcodes fixed"
  end
end
